openapi: "3.0.0"
info:
  version: 1.0.0
  title: dribblr
servers:
  - url: http://localhost:4000/api
tags:
  - name: 'Authorisation'
    description: 'Everything about login and registration.'
  - name: 'League'
    description: 'Everything about league, including league seasons and league admins.'
  - name: 'Season'
    description: 'Everything about season, including season grades.'
  - name: 'Grade'
    description: 'Everything about grade, including grade teams.'
  - name: 'Team'
    description: 'Everything about teams.'
  - name: 'Round'
    description: 'Everything about rounds.'
