name: gcp-deploy

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Build with Cloud Build
        working-directory: ./server
        run: |-
          gcloud builds submit --quiet --config ./cloudbuild.yaml

      - name: Deploy on Cloud Run
        working-directory: ./server
        run: |-
          gcloud run deploy --set-env-vars "MONGO_CONNECTION_URI=${{ secrets.MONGO_CONNECTION_URI }},JWT_SECRET=${{ secrets.JWT_SECRET }}" dribblr --image gcr.io/$PROJECT_ID/dribblr
