name: API Tests CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./server

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: ['4.2', '4.4']

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: yarn
      working-directory: ${{env.working-directory}}
    - run: yarn test
      working-directory: ${{env.working-directory}}
      env:
        JWT_SECRET: aaaaaaaaaaaaaaaaaaaaaaaaa
