name: Client Tests CI

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            working-directory: ./client
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: yarn
            - name: Run tests
              run: yarn test
